name: Render and deploy the book

on:
  push

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: actions/setup-python@v4

      - name: Update Jinja2 
        run: pip install jinja2 --upgrade
      
      - name: Install Jupyter
        run: pip install jupyterlab notebook PyQt5 sip GDAL

      - name: Install PyQt5
        run: pip install PyQt5 sip
      
      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt upgrade
          sudo apt-get install gdal gdal-bin
          pip install GDAL

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: "Deploy to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
